# goreleaser documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - freebsd
    - linux
    - windows
    - darwin
  ignore:
        - goos: darwin
          goarch: 386
        - goos: windows
          goarch: 386
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

signs:
  -
    signature: "${artifact}.sig"
    artifacts: all
    cmd: keybase
    args:
    - sign
    - --infile
    - $artifact
    - --binary
    - --outfile
    - $signature
    - --detached
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
